JARS:
    LLR_JAR: "llr-assembly-1.2.jar"
    EMBEDDINGS_JAR: "n2v-assembly-3.7.jar"
    PREDICTIONS_JAR: "prediction-assembly-2.2.jar"
    EVALUATION_JAR: "evaluation-assembly-1.1.jar"
PATHS:
    JARS: "s3://sandbox-l2v/JARs/"
    OUTPUT: "s3://sandbox-l2v/datasets/ml-1m/"
DATA:
    TRAIN: "s3://sandbox-l2v/datasets/ml-1m/split/split-cleaned-formatted-4and5/ml1m-train-clean4and5"
    VALIDATION: "s3://sandbox-l2v/datasets/ml-1m/split/split-cleaned-formatted/ml1m-validation-clean"
    TRAIN-VALIDATION: ""
    TEST: ""
